import Header from "@/components/Header";

import "./globals.css";
import { Inter, Miniver, Poppins } from "next/font/google";


const inter = Inter({
  subsets: ["latin"],
  variable: "--inter",
  weight: ["100", "300", "400", "500", "600", "700", "800", "900"],
});

const miniver = Miniver({
  subsets: ["latin"], 
  weight: ["400"],
  variable: "--miniver",

});

const poppins = Poppins({
  subsets: ["latin"], 
  weight: ["100", "300", "500", "400", "600", "700"],

  variable: "--poppins",
});


export const metadata = {
  title: "Resturant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${miniver.variable} ${poppins.variable}  px-20 py-2 `}
      >
        <Header />
        
        {children}
      </body>
    </html>
  );
}
