export const MenuList = {
  food: {
    breakfast: [
      {
        id: 1,
        name: "Scrambled Eggs",
        price: 5.99,
        calories: 150,
        description: "Fluffy scrambled eggs seasoned to perfection.",
      },
      {
        id: 2,
        name: "Bacon",
        price: 3.99,
        calories: 80,
        description: "Crispy strips of bacon.",
      },
      {
        id: 3,
        name: "Toast",
        price: 2.49,
        calories: 70,
        description: "Slices of toasted bread.",
      },
      {
        id: 4,
        name: "Oatmeal",
        price: 4.49,
        calories: 120,
        description: "Creamy oatmeal with your choice of toppings.",
      },
      {
        id: 5,
        name: "Fruit Salad",
        price: 6.99,
        calories: 90,
        description: "Fresh fruit salad with a variety of seasonal fruits.",
      },
      {
        id: 21,
        name: "Pancakes",
        price: 7.49,
        calories: 350,
        description: "Fluffy pancakes served with maple syrup and butter.",
      },
      {
        id: 22,
        name: "French Toast",
        price: 6.99,
        calories: 280,
        description: "Thick slices of bread soaked in egg batter and grilled.",
      },
      {
        id: 23,
        name: "Breakfast Burrito",
        price: 8.99,
        calories: 420,
        description:
          "Scrambled eggs, cheese, and sausage wrapped in a tortilla.",
      },
      {
        id: 24,
        name: "Bagel with Cream Cheese",
        price: 4.99,
        calories: 320,
        description: "Toasted bagel with a generous spread of cream cheese.",
      },
      {
        id: 25,
        name: "Avocado Toast",
        price: 9.49,
        calories: 280,
        description: "Sliced avocado on whole-grain toast with seasonings.",
      },
      {
        id: 26,
        name: "Waffle with Berries",
        price: 8.99,
        calories: 320,
        description:
          "Crispy waffle topped with fresh berries and whipped cream.",
      },
      // Add more breakfast items here
    ],
    lunch: [
      {
        id: 6,
        name: "Grilled Chicken Salad",
        price: 8.99,
        calories: 250,
        description: "Grilled chicken breast on a bed of mixed greens.",
      },
      {
        id: 7,
        name: "Vegetable Soup",
        price: 4.99,
        calories: 120,
        description: "Homemade vegetable soup.",
      },
      {
        id: 8,
        name: "Turkey Sandwich",
        price: 7.49,
        calories: 350,
        description: "Classic turkey sandwich with lettuce and tomato.",
      },
      {
        id: 9,
        name: "Quinoa Salad",
        price: 9.99,
        calories: 200,
        description: "Nutritious quinoa salad with vegetables and vinaigrette.",
      },
      {
        id: 10,
        name: "Sushi Roll",
        price: 12.99,
        calories: 180,
        description: "Assorted sushi rolls with soy sauce and wasabi.",
      },
      // Add more lunch items here
    ],
    dinner: [
      {
        id: 11,
        name: "Salmon with Asparagus",
        price: 14.99,
        calories: 300,
        description: "Grilled salmon fillet served with roasted asparagus.",
      },
      {
        id: 12,
        name: "Steak with Mashed Potatoes",
        price: 18.99,
        calories: 450,
        description: "Juicy steak with creamy mashed potatoes.",
      },
      {
        id: 13,
        name: "Pasta with Tomato Sauce",
        price: 11.49,
        calories: 350,
        description: "Pasta served with homemade tomato sauce.",
      },
      {
        id: 14,
        name: "Stir-Fried Tofu and Vegetables",
        price: 10.99,
        calories: 280,
        description: "Tofu and vegetables stir-fried in a savory sauce.",
      },
      {
        id: 15,
        name: "Baked Cod",
        price: 13.49,
        calories: 220,
        description: "Oven-baked cod with lemon and herbs.",
      },
      // Add more dinner items here
    ],
    dessert: [
      {
        id: 16,
        name: "Chocolate Cake",
        price: 6.99,
        calories: 300,
        description: "Decadent chocolate cake with fudge frosting.",
      },
      {
        id: 17,
        name: "Fruit Sorbet",
        price: 4.49,
        calories: 120,
        description: "Refreshing fruit sorbet in assorted flavors.",
      },
      {
        id: 18,
        name: "Cheesecake",
        price: 7.99,
        calories: 400,
        description: "Creamy cheesecake with a graham cracker crust.",
      },
      {
        id: 19,
        name: "Ice Cream",
        price: 5.49,
        calories: 250,
        description: "Rich and creamy ice cream in various flavors.",
      },
      {
        id: 20,
        name: "Fruit Tart",
        price: 8.99,
        calories: 180,
        description: "Delicious fruit tart with a buttery crust.",
      },
      {
        id: 21,
        name: "Tiramisu",
        price: 7.99,
        calories: 350,
        description:
          "Classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cheese.",
      },
      {
        id: 22,
        name: "Fruit Parfait",
        price: 5.49,
        calories: 180,
        description:
          "Layered dessert with yogurt, granola, and a variety of fresh fruits.",
      },
      {
        id: 23,
        name: "Molten Chocolate Lava Cake",
        price: 8.49,
        calories: 400,
        description:
          "Warm and gooey chocolate cake with a molten chocolate center.",
      },
    ],
    drink: [
      {
        id: 21,
        name: "Water",
        price: 1.99,
        calories: 0,
        description: "Refreshing and calorie-free water.",
      },
      {
        id: 22,
        name: "Orange Juice",
        price: 3.49,
        calories: 120,
        description: "Freshly squeezed orange juice.",
      },
      {
        id: 23,
        name: "Iced Tea",
        price: 2.99,
        calories: 10,
        description: "Chilled iced tea with a hint of lemon.",
      },
      {
        id: 24,
        name: "Cappuccino",
        price: 4.99,
        calories: 150,
        description: "Creamy cappuccino with a dusting of cocoa.",
      },
      {
        id: 25,
        name: "Soda",
        price: 1.99,
        calories: 140,
        description: "Carbonated soda in various flavors.",
      },
      {
        id: 26,
        name: "Freshly Squeezed Lemonade",
        price: 3.99,
        calories: 120,
        description: "Tangy and refreshing lemonade made with fresh lemons.",
      },
      {
        id: 27,
        name: "Mango Lassi",
        price: 4.49,
        calories: 220,
        description:
          "Creamy yogurt-based mango smoothie with a hint of cardamom.",
      },
      {
        id: 28,
        name: "Green Tea",
        price: 2.99,
        calories: 0,
        description: "Hot or iced green tea with antioxidants.",
      },
    ],
  },
};
